/** 10 weapons — damage from strong to weak (+ FIST for melee bots) */
export const WEAPONS = {
  FIST: {
    id: 'FIST',
    name: 'Đấm tay không',
    type: 'melee',
    damage: 10, // 10 đấm = chết (100 HP)
    fireRate: 0.5,
    clipSize: 999,
    reserve: 999,
    reloadTime: 0.1,
    spread: 0,
    adsSpread: 0,
    range: 2.8,
    color: 0x111111,
    accent: 0x333333,
    longBarrel: false,
    melee: true,
  },
  AWP: {
    id: 'AWP',
    name: 'Súng Ngắm AWP',
    type: 'sniper',
    damage: 100,
    fireRate: 1.2,
    clipSize: 5,
    reserve: 20,
    reloadTime: 3.2,
    spread: 0.002,
    adsSpread: 0.0005,
    range: 200,
    color: 0xc4782a,
    accent: 0x555555,
    longBarrel: true,
  },
  AK47: {
    id: 'AK47',
    name: 'AK-47',
    type: 'rifle',
    damage: 36,
    fireRate: 0.1,
    clipSize: 30,
    reserve: 90,
    reloadTime: 2.4,
    spread: 0.028,
    adsSpread: 0.012,
    range: 120,
    color: 0x3a3a3a,
    accent: 0xb85c1a,
    longBarrel: false,
  },
  M4A1: {
    id: 'M4A1',
    name: 'M4A1',
    type: 'rifle',
    damage: 33,
    fireRate: 0.09,
    clipSize: 30,
    reserve: 90,
    reloadTime: 2.2,
    spread: 0.022,
    adsSpread: 0.01,
    range: 130,
    color: 0x2a2a2a,
    accent: 0x6b4423,
    longBarrel: false,
  },
  MP31: {
    id: 'MP31',
    name: 'MP31',
    type: 'smg',
    damage: 26,
    fireRate: 0.07,
    clipSize: 35,
    reserve: 105,
    reloadTime: 2.0,
    spread: 0.035,
    adsSpread: 0.018,
    range: 70,
    color: 0x222222,
    accent: 0x444444,
    longBarrel: false,
  },
  UMP45: {
    id: 'UMP45',
    name: 'UMP-45',
    type: 'smg',
    damage: 28,
    fireRate: 0.09,
    clipSize: 25,
    reserve: 100,
    reloadTime: 2.1,
    spread: 0.03,
    adsSpread: 0.015,
    range: 75,
    color: 0x333333,
    accent: 0x555555,
    longBarrel: false,
  },
  DEAGLE: {
    id: 'DEAGLE',
    name: 'Desert Eagle',
    type: 'pistol',
    damage: 53,
    fireRate: 0.35,
    clipSize: 7,
    reserve: 35,
    reloadTime: 2.0,
    spread: 0.02,
    adsSpread: 0.008,
    range: 80,
    color: 0x888888,
    accent: 0x222222,
    longBarrel: false,
  },
  GLOCK: {
    id: 'GLOCK',
    name: 'Glock-18',
    type: 'pistol',
    damage: 22,
    fireRate: 0.15,
    clipSize: 20,
    reserve: 120,
    reloadTime: 1.8,
    spread: 0.025,
    adsSpread: 0.012,
    range: 50,
    color: 0x1a1a1a,
    accent: 0xffaa00,
    longBarrel: false,
  },
  NOVA: {
    id: 'NOVA',
    name: 'Nova Shotgun',
    type: 'shotgun',
    damage: 20,
    pellets: 8,
    fireRate: 0.85,
    clipSize: 8,
    reserve: 32,
    reloadTime: 3.5,
    spread: 0.08,
    adsSpread: 0.05,
    range: 35,
    color: 0x4a3728,
    accent: 0x222222,
    longBarrel: false,
  },
  P90: {
    id: 'P90',
    name: 'P90',
    type: 'smg',
    damage: 24,
    fireRate: 0.06,
    clipSize: 50,
    reserve: 100,
    reloadTime: 2.8,
    spread: 0.04,
    adsSpread: 0.02,
    range: 60,
    color: 0x2c3e50,
    accent: 0x1abc9c,
    longBarrel: false,
  },
  USP: {
    id: 'USP',
    name: 'USP-S',
    type: 'pistol',
    damage: 30,
    fireRate: 0.22,
    clipSize: 12,
    reserve: 24,
    reloadTime: 1.9,
    spread: 0.018,
    adsSpread: 0.007,
    range: 55,
    color: 0xcccccc,
    accent: 0xff6600,
    longBarrel: false,
  },
};

export const WEAPON_IDS = Object.keys(WEAPONS).filter((id) => id !== 'FIST');

export function randomWeaponId() {
  return WEAPON_IDS[Math.floor(Math.random() * WEAPON_IDS.length)];
}

export function createWeaponState(weaponId) {
  const w = WEAPONS[weaponId];
  return {
    id: weaponId,
    clip: w.clipSize,
    reserve: w.reserve,
    lastShot: 0,
    reloading: false,
    reloadEnd: 0,
  };
}
